name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: write
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Read secrets
        uses: rancher-eio/read-vault-secrets@0da85151ad1f19ed7986c41587e45aac1ace74b6 # main
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username |  DOCKER_USERNAME;
            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password |  DOCKER_PASSWORD;

      - name: Push images
        uses: rancher/ecm-distro-tools/actions/publish-image@575bb831c67edd950bfedb59d41dd127bd0005d6 # master
        with:
          image: llm-mock
          tag: ${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64

          public-repo: rancher-sandbox
          public-username: ${{ env.DOCKER_USERNAME }}
          public-password: ${{ env.DOCKER_PASSWORD }}
          push-to-public: true
          push-to-prime: false
          make-target: push-image
